### ISSUE TITLE
Question: how to install golang based chaincodes

### ISSUE THREAD

**Issue by jchai002** [APGGroeiFabriek/PIVT#28]
I noticed that the sample chaincodes in this project are written with nodeJS, but I'm having trouble instantiation golang based chaincode.

**What I did:**

I copied the 3 files from here: 

https://github.com/hyperledger/fabric-samples/tree/master/chaincode/fabcar/go 

and put the files into the directory `/samples/chaincode/fabcar` 

in `simple/network.yaml` I added this under the chaincode section:

```
- name: fabcar
      # if defined, this will override the global chaincode.version value
      version: # "2.0"
      # chaincode will be installed to all peers in these organizations
      orgs: [Karga, Nevergreen, Atlantis]
      # at which channels are we instantiating/upgrading chaincode?
      channels:
      - name: common
        # chaincode will be instantiated/upgraded using the first peer in the first organization
        # chaincode will be invoked on all peers in these organizations
        orgs: [Karga, Nevergreen, Atlantis]
        policy: OR('KargaMSP.member','NevergreenMSP.member','AtlantisMSP.member')
```

I then ran the init script to package the chaincodes into tar files, and had the `fabcar.tar` file created.

When I try to install and instantiate the chaincode, the output shows that the chaincode was installed, but all the instantiate steps failed:

<img width="1332" alt="Screen Shot 2020-01-02 at 5 11 29 AM" src="https://user-images.githubusercontent.com/11948171/71668596-5c5ba480-2d1e-11ea-8b2e-9c79a9ff5c17.png">

Is there something other configs that I need to do to use golang chaincodes?
