### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by asghaier76** [APGGroeiFabriek/PIVT#44]
I am running this on IBM kubernetes and as I start the workflow for channels creation it shows that pods initializing and after that the following error comes up 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? message.

The init script ran fine and also the command
```
helm install ./hlf-kube --name hlf-kube -f samples/simple/network.yaml -f samples/simple/crypto-config.yaml
```
right after that when I check the running pods I can see the ca, peer and orderer pods ruuning

The environment I am using 

kubectl version
```
clientVersion:
  buildDate: "2020-03-26T06:16:15Z"
  compiler: gc
  gitCommit: 9e991415386e4cf155a24b1da15becaa390438d8
  gitTreeState: clean
  gitVersion: v1.18.0
  goVersion: go1.14
  major: "1"
  minor: "18"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-13T14:13:41Z"
  compiler: gc
  gitCommit: c6910e70b932ed9ffe5baedade2274a72925660f
  gitTreeState: clean
  gitVersion: v1.16.8+IKS
  goVersion: go1.13.8
  major: "1"
  minor: "16"
  platform: linux/amd64
```

argo version
```
argo: v2.7.2
  BuildDate: 2020-04-10T19:25:22Z
  GitCommit: c52a65aa62426f5e874e1d3f1058af15c43eb35f
  GitTreeState: clean
  GitTag: v2.7.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```

helm version
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
