### ISSUE TITLE
Persistent Volume Claims Are not Consumed. Is Dynamic Provisioning Necessary?

### ISSUE THREAD

**Issue by paulrusu8** [APGGroeiFabriek/PIVT#48]
I am trying to run the scaled raft tls sample with persistence enabled, but it is noted that the persistent volume claims are not consumed. Does this mean that a form of dynamic provisioning is necessary?

**Comment by raftAtGit** [comment]
Sorry, what do you mean by "the persistent volume claims are not consumed"?

**Comment by paulrusu8** [comment]
What I mean is that in the templates, there is only the statefulset, but no persistent-volume which consumes the persistent volume claim from the template, as for example in orderer-statefulset.yaml:

```
volumeClaimTemplates:
  {{- if $.Values.orderer.persistence.enabled }}
  - metadata:
      name: orderer-disk
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ $.Values.persistence.storageClass }}
      resources:
        requests:
          storage: {{ $.Values.orderer.persistence.size }}


```

Therefore, the created pods are in a pending state and the associated pvc display the message that 

`Normal  ExternalProvisioning  9s (x6 over 72s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "cinder.csi.openstack.org" or manually created by system administrator`

Have you seen this before ?
