### ISSUE TITLE
network.yaml with multiple channels of just one org each fails with chaincode invocation flow 

### ISSUE THREAD

**Issue by sillysachin** [APGGroeiFabriek/PIVT#61]
https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/samples/scaled-raft-no-tls/network.yaml

**Failure Message**

**├-✖ maybe-instantiate-or-upgrade-chaincode--simple-1-0--private-karga--Karga--peer0(9)                 maybe-instantiate-or-upgrade-chaincode--simple-1-0--private-karga--Karga--peer0                   hlf-chaincodes-xrhc4-3031688089  15s       failed with exit code 1**

**Files Updated**

in network.yaml file
```
##Channels
channels:
- name: common
orgs: [Karga, Nevergreen, Atlantis]
- name: private-karga-atlantis
orgs: [Karga, Atlantis]

channels:
- name: common
orgs: [Karga, Nevergreen, Atlantis]
- name: private-karga-atlantis
orgs: [Karga, Atlantis]
- name: private-karga
orgs: [Karga]
- name: private-atlantis
orgs: [Atlantis]

## Chaincode
chaincodes:
- name: even-simpler
  language: golang
  orgs: [Karga, Atlantis]
  channels:
  - name: private-atlantis
	orgs: [Atlantis]
	policy: OR('AtlantisMSP.member')
  - name: private-karga
	orgs: [Karga]
	policy: OR('KargaMSP.member')

```
in configtx.yaml file added

```
private-karga:
    Consortium: TheConsortium
    <<: *ChannelDefaults
    Application:
        <<: *ApplicationDefaults
        Organizations:
            - *Karga

private-atlantis:
    Consortium: TheConsortium
    <<: *ChannelDefaults
    Application:
        <<: *ApplicationDefaults
        Organizations:
            - *Atlantis

```
